export const LOGIN_ON_CHANGE = "LOGIN_ON_CHANGE";
export const LOGIN_ON_SUBMIT = "LOGIN_ON_SUBMIT";
export const SET_LOGIN_PENDING = "SET_LOGIN_PENDING";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SIGNUP_ON_CHANGE = "SIGNUP_ON_CHANGE";
export const SIGNUP_ON_SUBMIT = "SIGNUP_ON_SUBMIT";
export const SET_SIGNUP_PENDING = "SET_SIGNUP_PENDING";
export const SET_SIGNUP_SUCCESS = "SET_SIGNUP_SUCCESS";
export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAILED = "FETCH_SERVICES_FAILED";
export const SAVE_SERVICES_SUCCESS = "SAVE_SERVICES_SUCCESS";
export const SAVE_SERVICES_ERROR = "SAVE_SERVICES_ERROR";
export const UPDATE_SERVICES_SUCCESS = "UPDATE_SERVICES_SUCCESS";
export const UPDATE_SERVICES_ERROR = "UPDATE_SERVICES_ERROR";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const ADD_SERVICE = "ADD_SERVICE";
export const USER_MENU_TOGGLE = "USER_MENU_TOGGLE";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const SERVICE_TO_EDIT = "SERVICE_TO_EDIT";

export const CurrentUserActions = {
  CURRENT_USER: "CURRENT_USER"
};
export const DialogActionType = {
  ON_DIALOG_TOGGLE: "ON_DIALOG_TOGGLE",
  ON_SERVICE_DIALOG_TOGGLE: "ON_SERVICE_DIALOG_TOGGLE"
};

export const DrawerActionType = {
  ON_DRAWER_TOGGLE: "ON_DRAWER_TOGGLE"
};

export const FormActionType = {
  ON_SERVICE_FORM_CHANGE: "ON_SERVICE_FORM_CHANGE",
  ON_SERVICE_FORM_SUBMIT: "ON_SERVICE_FORM_SUBMIT",
  FORM_SUCCESS: "FORM_SUCCESS",
  FORM_ERROR: "FORM_ERROR",
  FORM_TYPE: "FORM_TYPE"
};
